### ISSUE TITLE
Intention behind git config

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.build#1]
why does aardpack set the git config?                 

```Git.CommandHelper.directRunGitCommandAndFail workdir "config --local user.name \"aardvark-platform\""
Git.CommandHelper.directRunGitCommandAndFail workdir "config --local user.email \"admin@aardvarkians.com\"" ```
what's the idea behind it?

**Comment by krauthaufen** [comment]
Cannot push tags on the CI otherwise

**Comment by haraldsteinlechner** [comment]
this silently trapped me into several times till i spotted it here:
![image](https://user-images.githubusercontent.com/513281/164441847-57742c4f-ba5e-401b-a4e7-a6cb89234d14.png)

i thought this config is solely informatively. I think either changing it back or not doing it depending on stuff would be the way to go not sure...

**Comment by hyazinthh** [comment]
This should not happen anyway unless GITHUB_TOKEN is defined. Can this be closed?
