### ISSUE TITLE
Changes needed for flexible RELEASE_NOTEST/version

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.build#2]
what would be needed to aardvark.build and aardpack not depend on release_notes.md.
use case: have 2 release_notes since it is used to build a product as well as packages.

in aardpack it could be a command line arg? in the msbuild target as well?

**Comment by krauthaufen** [comment]
You could put them in separate directories and set the `<RepositoryRoot>` property in msbuild to one or the other folder

**Comment by haraldsteinlechner** [comment]
just checked, no does not work, since native dependency injection should be separate and independent of the release_notes file. i think best way is make release_notes_path property of msbuild task and argument to the tool can give it a try if this is the way to go
