### ISSUE TITLE
aardpack fails if no vs2019 is present

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.build#5]
just after start, FAKE tries to spot msbuild... i updated fake but still no luck. looks like this:
![image](https://user-images.githubusercontent.com/513281/205644926-9d8c94e6-a749-4671-904f-039300360759.png)

will investigate further, but this is also a reason for the custom build steps for creating the package.

**Comment by hyazinthh** [comment]
I don't have VS2019 on my systems and have never seen this error.

**Comment by haraldsteinlechner** [comment]
Thanks for the hint!! found out, this happens if you have a zombie environment variable %MSBUILD% which i created at some point.
